export const ADD_USER = 'ADD_USER';
export const GET_FEATURED_ALBUMS = 'GET_FEATURED_ALBUMS';

export const GET_ALBUM_DETAILS = 'GET_ALBUM_DETAILS';
export const CLEAR_ALBUM_DETAILS = 'CLEAR_ALBUM_DETAILS';

export const GET_ALBUMS_BY_GENRES = 'GET_ALBUMS_BY_GENRES';
export const GET_ALBUMS_IN_GENRE = 'GET_ALBUMS_IN_GENRE';

export const GET_NEW_RELEASES = 'GET_NEW_RELEASES';
export const GET_NEW_RELEASE_DETAILS = 'GET_NEW_RELEASE_DETAILS';
export const CLEAR_NEW_RELEASE_DETAILS = 'CLEAR_NEW_RELEASE_DETAILS';

export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
export const GET_USER_FOLLOWED_ARTISTS = 'GET_USER_FOLLOWED_ARTISTS';
export const GET_USER_SAVED_ALBUMS = 'GET_USER_SAVED_ALBUMS';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';

export const GET_ARTIST = 'GET_ARTIST';
export const CLEAR_ARTIST = 'CLEAR_ARTIST';

export const SEARCH = 'SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
